wandb:
  entity: jinkyusung-snu
  project: SR-baselines
  run_id: None

dataset:
  name: amazon-beauty
  k_core: 5
  max_len: 50
  batch_size: 512

model:
  name: JODIE
  emb_dim: 128

trainer:
  name: JODIETrainer
  epochs: 50
  lr: 0.001
  weight_decay: 0.0001
