wandb:
  entity: jinkyusung-snu
  project: SR-baselines
  run_id: None

dataset:
  name: tmall-click
  k_core: 10
  max_len: 50
  batch_size: 512

model:
  name: JODIE
  num_layer: 5
  emb_dim: 64

trainer:
  name: JODIETrainer
  epochs: 2000
  lr: 0.001
  weight_decay: 0.0005
